<main id="main">
<header class="page-hero page-hero--image blog-hero">
	<div class="page-hero__media"><img class="page-hero__image" src="assets/images/blog-insights-1280.jpg" srcset="assets/images/blog-insights-480.jpg 480w, assets/images/blog-insights-768.jpg 768w, assets/images/blog-insights-1280.jpg 1280w, assets/images/blog-insights.jpg 1672w" sizes="100vw" width="1672" height="941" alt="Canadian financial professional reviewing an article in a modern office" fetchpriority="high" decoding="async"><span class="page-hero__overlay"></span></div>
	<div class="container page-hero__content"><p class="eyebrow">Insights from Bajwa CPA</p><h1>Ideas for clearer financial decisions.</h1><p class="page-hero__intro">Practical Canadian tax, accounting and business guidance, written for the decisions that matter.</p><div class="blog-hero__tags" aria-label="Topics"><span>Personal tax</span><span>Business</span><span>Real estate</span><span>Planning</span></div></div>
</header>
<section class="section resource-intro"><div class="container resource-lead"><div><p class="eyebrow">Knowledge for better decisions</p><h2>Timely thinking for individuals and business owners.</h2></div><p>Explore personal tax, corporate planning, real estate, GST/HST and business guidance.</p></div></section>
<section class="section section--mist blog-library"><div class="container"><div class="blog-toolbar"><p><strong>Latest insights</strong><span>Tax · Accounting · Business</span></p></div><div class="blog-grid">
<?php $shown=0;foreach($blog_posts as $post):if(!in_array(10,$post['categories']??array(),true)&&$shown<5)continue;$fallback=$blog_image($post['slug']);$small=file_exists(__DIR__.'/assets/images/'.$fallback.'-600.jpg')?'-600':'-960';$small_w=$small==='-600'?600:960;$small_h=$small==='-600'?450:540;?>
	<article class="blog-card"><a class="blog-card__image" href="<?php echo $article_url($post['slug']); ?>"><img src="assets/images/<?php echo $fallback.$small; ?>.jpg" sizes="(max-width: 760px) 100vw, 33vw" width="<?php echo $small_w; ?>" height="<?php echo $small_h; ?>" loading="<?php echo $shown<3?'eager':'lazy'; ?>" fetchpriority="<?php echo $shown===0?'high':'low'; ?>" decoding="async" alt=""><span>Read article</span></a><div class="blog-card__body"><div class="blog-card__meta"><span><?php echo date('M j, Y',strtotime($post['date'])); ?></span><span>Insights</span></div><h2><a href="<?php echo $article_url($post['slug']); ?>"><?php echo strip_tags(html_entity_decode($post['title']['rendered'])); ?></a></h2><p><?php echo htmlspecialchars(substr(trim(strip_tags(html_entity_decode($post['excerpt']['rendered']))),0,120)); ?>&hellip;</p><a class="text-link" href="<?php echo $article_url($post['slug']); ?>">Continue reading <?php echo $arrow; ?></a></div></article>
<?php $shown++;if($shown>=9)break;endforeach;?>
</div></div></section></main>
