<?php get_header(); ?>
<main id="main">
	<?php bajwa_render_hero(); ?>
	<section class="assurance-band"><div class="container assurance-grid">
		<article class="assurance-item"><span class="assurance-icon">01</span><div><h2>Quality professional services</h2><p>Your accounting and taxation are handled with care, accuracy and close attention to detail.</p></div></article>
		<article class="assurance-item"><span class="assurance-icon">02</span><div><h2>Year-round support</h2><p>We remain available beyond filing season, helping you prepare early and make better decisions.</p></div></article>
		<article class="assurance-item"><span class="assurance-icon">03</span><div><h2>Friendly, approachable team</h2><p>A welcoming environment, personal service and clear explanations set our firm apart.</p></div></article>
	</div></section>
	<section class="section home-welcome"><div class="container editorial-split">
		<div class="editorial-photo"><img src="<?php echo esc_url(get_theme_file_uri('assets/images/page-about.jpg')); ?>" srcset="<?php echo esc_url(get_theme_file_uri('assets/images/page-about-960.jpg')); ?> 960w, <?php echo esc_url(get_theme_file_uri('assets/images/page-about-1280.jpg')); ?> 1280w, <?php echo esc_url(get_theme_file_uri('assets/images/page-about.jpg')); ?> 1672w" sizes="(max-width:760px) 100vw, 48vw" width="1672" height="941" loading="lazy" decoding="async" alt="Business owners meeting with a professional advisor in a modern Toronto office"><span class="editorial-photo__badge"><strong>CPA</strong>Professional guidance</span></div>
		<div class="editorial-copy"><p class="eyebrow">Helping clients big and small</p><h2>Tax and accounting guidance that makes the complicated feel manageable.</h2><p class="lead">Welcome to Bajwa CPA Professional Corporation, your CPA and tax specialists in the Greater Toronto Area.</p><p>Whether you are an established company, a self-employed entrepreneur or an individual filing a personal return, our team brings experience, dedication and current knowledge of Canadian accounting regulations and tax law.</p><p>We work to minimize tax liabilities, maximize available refunds and make financial administration less stressful.</p><a class="button button--navy" href="<?php echo esc_url(home_url('/about-us/')); ?>">Discover our approach <?php echo bajwa_icon('arrow'); ?></a></div>
	</div></section>
	<section id="home-services" class="section home-services section--mist"><div class="container">
		<div class="section-heading section-heading--center"><div><p class="eyebrow">Core expertise</p><h2>Services designed around the decisions you face.</h2><p>Strategic advice and careful compliance work for individuals, entrepreneurs and corporations.</p></div></div>
		<div class="visual-service-grid"><?php $featured_slugs=array('corporate-tax-return','business-tax-return','personal-tax-return','financial-statements','professional-corporations','hst-new-residential-rental-property-rebate','budgeting-forecasting','business-consulting'); $featured=get_posts(array('post_type'=>'service','numberposts'=>8,'post_name__in'=>$featured_slugs,'orderby'=>'post_name__in')); foreach($featured as $index=>$service): ?><a class="service-visual" href="<?php echo esc_url(get_permalink($service)); ?>"><div class="service-visual__media"><?php echo bajwa_service_card_image($service->ID); ?><span class="service-visual__shade"></span><span class="service-visual__index"><?php echo esc_html(str_pad($index+1,2,'0',STR_PAD_LEFT)); ?></span></div><div class="service-visual__body"><h3><?php echo esc_html(get_the_title($service)); ?></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt($service),18)); ?></p><span class="service-visual__link">Explore service <?php echo bajwa_icon('arrow'); ?></span></div></a><?php endforeach; ?></div>
	</div></section>
	<section class="section service-directory"><div class="container directory-layout"><div class="directory-intro"><p class="eyebrow">A broad range of CPA services</p><h2>One trusted team for your changing financial needs.</h2><p>Monthly bookkeeping, tax returns, financial statements, planning and advisory support—all delivered with professional accountability and personal attention.</p><a class="text-link" href="<?php echo esc_url(get_post_type_archive_link('service')); ?>">See all services <?php echo bajwa_icon('arrow'); ?></a></div><div class="service-mini-list"><?php $all_services=get_posts(array('post_type'=>'service','numberposts'=>-1,'orderby'=>'menu_order','order'=>'ASC')); foreach($all_services as $service): ?><a href="<?php echo esc_url(get_permalink($service)); ?>"><span class="service-mini-list__image"><?php echo bajwa_service_card_image($service->ID,''); ?></span><strong><?php echo esc_html(get_the_title($service)); ?></strong><?php echo bajwa_icon('arrow'); ?></a><?php endforeach; ?></div></div></section>
	<section class="results-section"><div class="container results-grid"><div><span class="result-number">500+</span><p>Recurring clients</p></div><div><span class="result-number">1,000+</span><p>Returns processed</p></div><div><span class="result-number">10+</span><p>Years of experience</p></div><div class="results-statement"><p>Professional expertise.<br><em>Personal commitment.</em></p></div></div></section>
	<section class="section finance-story"><div class="container editorial-split editorial-split--reverse"><div class="editorial-copy"><p class="eyebrow">Streamlining your finances</p><h2>Year-round support that helps you keep more and plan further ahead.</h2><p class="lead">Our CPAs and tax specialists bring a broad set of financial skills and a deep understanding of Canadian compliance.</p><p>Whether you need one-time help with personal taxes or have a sophisticated profile with multiple income streams, we help structure your affairs for growth, profitability and fewer surprises.</p><ul class="premium-list"><li><?php echo bajwa_icon('check'); ?><span>Practical advice for individuals and self-employed professionals</span></li><li><?php echo bajwa_icon('check'); ?><span>Corporate structure, compliance and growth planning</span></li><li><?php echo bajwa_icon('check'); ?><span>Responsive support for non-residents and property investors</span></li></ul></div><div class="editorial-photo editorial-photo--portrait"><img src="<?php echo esc_url(get_theme_file_uri('assets/images/service-books.jpg')); ?>" srcset="<?php echo esc_url(get_theme_file_uri('assets/images/service-books-960.jpg')); ?> 960w, <?php echo esc_url(get_theme_file_uri('assets/images/service-books-1280.jpg')); ?> 1280w, <?php echo esc_url(get_theme_file_uri('assets/images/service-books.jpg')); ?> 1672w" sizes="(max-width:760px) 100vw, 48vw" width="1672" height="941" loading="lazy" decoding="async" alt="Organized professional accounting workspace with financial charts"></div></div></section>
	<section class="section industries-premium"><div class="container industries-shell"><div class="industries-copy"><p class="eyebrow">We love to see clients succeed</p><h2>Experience across the GTA’s essential industries.</h2><p>Our reputation is built on satisfied clients and recommendations. We understand the financial realities behind professional practices, property, retail and growing companies.</p><a class="text-link" href="<?php echo esc_url(home_url('/contact/')); ?>">Discuss your industry <?php echo bajwa_icon('arrow'); ?></a></div><div class="industry-grid"><?php $industries=array(array('Consultants','Advisory practices'),array('Doctors','Medical professionals'),array('Travel agencies','Travel businesses'),array('Dentists','Dental practices'),array('Chiropractors','Health practices'),array('Startups','Emerging companies'),array('Construction','Trades & contractors'),array('Retail','Stores & commerce'),array('Automotive','Dealers & services'),array('Food & entertainment','Hospitality businesses'),array('Real estate & brokerage','Property professionals'),array('Financial services','Finance practices'),array('Franchises','Single and multi-location operators')); foreach($industries as $i=>$industry): ?><div class="industry-tile<?php echo 12===$i?' industry-tile--wide':''; ?>"><span><?php echo esc_html(str_pad($i+1,2,'0',STR_PAD_LEFT)); ?></span><div><strong><?php echo esc_html($industry[0]); ?></strong><small><?php echo esc_html($industry[1]); ?></small></div><i aria-hidden="true">↗</i></div><?php endforeach; ?></div></div></section>
	<section class="section section--navy testimonial-stage"><div class="container"><div class="section-heading testimonial-heading"><div><p class="eyebrow">Client perspective</p><h2>Trusted for knowledge, care and attention to detail.</h2><p>Long-term relationships are built through clear answers, responsive support and work that gives clients confidence in every important financial decision.</p></div></div><div class="testimonial-carousel" data-testimonial-carousel aria-roledescription="carousel" aria-label="Client testimonials"><div class="testimonial-track"><blockquote><p>“It has been a pleasure working with Bajwa CPA. A dedicated and trusted Chartered Professional Accounting firm in the GTA.”</p><cite>Ritu Rani</cite></blockquote><blockquote><p>“The best tax advisor I have worked with—knowledgeable, dedicated and always willing to go above and beyond.”</p><cite>Gaya Nathan</cite></blockquote><blockquote><p>“Professional service with impressive attention to detail. Our personal and corporate filings were handled seamlessly.”</p><cite>Rai Zaman</cite></blockquote><blockquote><p>“Rapid, experienced and straightforward. You know you are working with someone who genuinely cares.”</p><cite>Aliza Pranav</cite></blockquote><blockquote><p>“Exceptional and professional corporate tax filing service. We highly recommend their services.”</p><cite>Gursh Singh</cite></blockquote></div><div class="testimonial-navigation"><button type="button" data-testimonial-prev aria-label="Previous testimonial">←</button><div class="testimonial-dots" aria-label="Choose testimonial"></div><button type="button" data-testimonial-next aria-label="Next testimonial">→</button></div></div></div></section>
	<section class="section home-final"><div class="container home-final__inner"><div><p class="eyebrow">Get started today</p><h2>Bring your questions.<br>Leave with a clearer direction.</h2><p>Work with a responsive CPA team that treats your finances with the care they deserve.</p></div><div class="home-final__actions"><a class="button button--gold" href="<?php echo esc_url(home_url('/contact/')); ?>">Work with us <?php echo bajwa_icon('arrow'); ?></a><a class="text-link" href="<?php echo esc_url(get_post_type_archive_link('service')); ?>">See all services</a></div></div></section>
	<?php if ( trim( (string) get_post_field( 'post_content', get_queried_object_id() ) ) ) : ?><section class="section home-editor-content"><div class="container prose"><?php the_content(); ?></div></section><?php endif; ?>
</main>
<?php get_footer(); ?>
