<?php
/**
 * Template Name: Blog
 */
get_header(); the_post(); ?>
<main id="main"><header class="page-hero page-hero--image blog-hero"><div class="page-hero__media"><img class="page-hero__image" src="<?php echo esc_url(get_theme_file_uri('assets/images/blog-insights.jpg')); ?>" srcset="<?php echo esc_url(get_theme_file_uri('assets/images/blog-insights-480.jpg')); ?> 480w, <?php echo esc_url(get_theme_file_uri('assets/images/blog-insights-768.jpg')); ?> 768w, <?php echo esc_url(get_theme_file_uri('assets/images/blog-insights-1280.jpg')); ?> 1280w, <?php echo esc_url(get_theme_file_uri('assets/images/blog-insights.jpg')); ?> 1672w" sizes="100vw" width="1672" height="941" alt="Tax professional reviewing financial insights for a Canadian business audience" fetchpriority="high"><span class="page-hero__overlay"></span></div><div class="container page-hero__content"><p class="eyebrow">Insights from Bajwa CPA</p><h1>Ideas for clearer financial decisions.</h1><p class="page-hero__intro">Practical Canadian tax, accounting and business guidance—explained clearly and written for real decisions.</p><div class="blog-hero__tags"><span>Personal tax</span><span>Business</span><span>Real estate</span><span>Planning</span></div></div></header>
<section class="section section--mist blog-library"><div class="container"><div class="blog-toolbar"><p><strong>Latest insights</strong><span>Tax · Accounting · Business</span></p></div><div class="blog-grid">
<?php $paged=max(1,(int)get_query_var('paged'),(int)get_query_var('page'));$q=new WP_Query(array('post_type'=>'post','posts_per_page'=>12,'paged'=>$paged,'ignore_sticky_posts'=>true));$i=0;while($q->have_posts()):$q->the_post();$fallback=bajwa_blog_image_name(get_the_ID());$small=file_exists(BAJWA_PREMIUM_DIR.'assets/images/'.$fallback.'-600.jpg')?'-600':'-960';?>
<article class="blog-card"><a class="blog-card__image" href="<?php the_permalink(); ?>"><?php if(has_post_thumbnail()):the_post_thumbnail('medium_large',array('loading'=>$i<3?'eager':'lazy','decoding'=>'async','fetchpriority'=>$i===0?'high':'auto'));else:?><img src="<?php echo esc_url(get_theme_file_uri('assets/images/'.$fallback.$small.'.jpg')); ?>" width="<?php echo '-600'===$small?'600':'960'; ?>" height="<?php echo '-600'===$small?'450':'540'; ?>" loading="<?php echo $i<3?'eager':'lazy'; ?>" decoding="async" alt="Illustration for <?php echo esc_attr(get_the_title()); ?>"><?php endif; ?><span>Read article</span></a><div class="blog-card__body"><div class="blog-card__meta"><span><?php echo esc_html(get_the_date('M j, Y')); ?></span><span><?php echo esc_html(max(1,ceil(str_word_count(wp_strip_all_tags(get_the_content()))/220))); ?> min read</span></div><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),18)); ?></p><a class="text-link" href="<?php the_permalink(); ?>">Continue reading <?php echo bajwa_icon('arrow'); ?></a></div></article>
<?php $i++;endwhile;wp_reset_postdata();?></div><?php if($q->max_num_pages>1): ?><nav class="blog-pagination" aria-label="Blog pages"><?php echo paginate_links(array('base'=>trailingslashit(get_permalink()).'%_%','format'=>'page/%#%/','current'=>$paged,'total'=>$q->max_num_pages,'prev_text'=>'&larr;','next_text'=>'&rarr;')); ?></nav><?php endif; ?></div></section></main><?php get_footer(); ?>
