<main id="main">
<header class="page-hero page-hero--image blog-hero">
	<div class="page-hero__media"><img class="page-hero__image" src="assets/images/blog-insights-1280.jpg" srcset="assets/images/blog-insights-480.jpg 480w, assets/images/blog-insights-768.jpg 768w, assets/images/blog-insights-1280.jpg 1280w, assets/images/blog-insights.jpg 1672w" sizes="100vw" width="1672" height="941" alt="Canadian financial professional reviewing an article in a modern office" fetchpriority="high" decoding="async"><span class="page-hero__overlay"></span></div>
	<div class="container page-hero__content"><p class="eyebrow">Insights from Bajwa CPA</p><h1>Ideas for clearer financial decisions.</h1><p class="page-hero__intro">Practical Canadian tax, accounting and business guidance, written for the decisions that matter.</p><div class="blog-hero__tags" aria-label="Topics"><span>Personal tax</span><span>Business</span><span>Real estate</span><span>Planning</span></div></div>
</header>
<section class="section section--mist blog-library"><div class="container"><div class="blog-toolbar"><p><strong>Latest insights</strong><span>Tax · Accounting · Business</span></p></div><div class="blog-grid">
<?php $all_posts=$blog_posts;usort($all_posts,static function($a,$b){return strcmp($b['date'],$a['date']);});$per_page=12;$total_pages=max(1,(int)ceil(count($all_posts)/$per_page));$cur_page=min($total_pages,max(1,(int)($_GET['pg']??1)));$shown=0;foreach(array_slice($all_posts,($cur_page-1)*$per_page,$per_page) as $post):$fallback=$blog_image($post['slug']);$small=file_exists(__DIR__.'/assets/images/'.$fallback.'-600.jpg')?'-600':'-960';$small_w=$small==='-600'?600:960;$small_h=$small==='-600'?450:540;?>
	<article class="blog-card"><a class="blog-card__image" href="<?php echo $article_url($post['slug']); ?>"><img src="assets/images/<?php echo $fallback.$small; ?>.jpg" sizes="(max-width: 760px) 100vw, 33vw" width="<?php echo $small_w; ?>" height="<?php echo $small_h; ?>" loading="<?php echo $shown<3?'eager':'lazy'; ?>" fetchpriority="<?php echo $shown===0?'high':'low'; ?>" decoding="async" alt=""><span>Read article</span></a><div class="blog-card__body"><div class="blog-card__meta"><span><?php echo date('M j, Y',strtotime($post['date'])); ?></span><span>Insights</span></div><h2><a href="<?php echo $article_url($post['slug']); ?>"><?php echo strip_tags(html_entity_decode($post['title']['rendered'])); ?></a></h2><p><?php echo htmlspecialchars(substr(trim(strip_tags(html_entity_decode($post['excerpt']['rendered']))),0,120)); ?>&hellip;</p><a class="text-link" href="<?php echo $article_url($post['slug']); ?>">Continue reading <?php echo $arrow; ?></a></div></article>
<?php $shown++;endforeach;?>
</div><?php if($total_pages>1): ?><nav class="blog-pagination" aria-label="Blog pages"><?php for($n=1;$n<=$total_pages;$n++): ?><a href="<?php echo $url('articles').($n>1?'?pg='.$n:''); ?>"<?php echo $n===$cur_page?' aria-current="page" class="is-current"':''; ?>><?php echo $n; ?></a><?php endfor; ?></nav><?php endif; ?></div></section></main>
