<?php
/** Standalone frontend preview. WordPress uses the regular theme templates instead. */
if ( PHP_SESSION_NONE === session_status() ) { session_start(); }
$services = array(
	'corporate-tax-return' => array( 'Corporate Tax Return', 'Accurate corporate filings, compliance and year-round tax guidance for companies of every size.' ),
	'business-tax-return' => array( 'Business Tax Return', 'Professional tax and accounting support for sole proprietors, partnerships and growing businesses.' ),
	'bookkeeping' => array( 'Bookkeeping', 'Reliable monthly bookkeeping that keeps your records current and decisions grounded in accurate numbers.' ),
	'personal-tax-return' => array( 'Personal Tax Return', 'Careful personal tax preparation designed to minimize stress and avoid missed credits or deductions.' ),
	'non-resident-tax-returns' => array( 'Non-Resident Tax Return', 'Canadian tax guidance for non-residents, newcomers and people with cross-border circumstances.' ),
	'real-estate-tax-returns' => array( 'Real Estate Tax Return', 'Tax preparation and planning for rental properties, dispositions and real estate professionals.' ),
	'trust-estate-tax-return' => array( 'Trust & Estate Tax Return', 'Sensitive, organized tax assistance for trusts, estates and executors.' ),
	'incorporation-business-registration' => array( 'Incorporation & Business Registration', 'Practical help choosing and establishing the right structure for your new business.' ),
	'financial-statements' => array( 'Financial Statements', 'Clear financial statements supporting compliance, lending and better business decisions.' ),
	'tax-planning' => array( 'Tax Planning', 'Forward-looking strategies for business owners, families and investors.' ),
	'professional-corporations' => array( 'Professional Corporations', 'Incorporation and tax guidance for regulated professionals.' ),
	'hst-new-residential-rental-property-rebate' => array( 'GST/HST Rental Property Rebate', 'Guidance for eligible rental-property rebate applications.' ),
	'budgeting-forecasting' => array( 'Budgeting & Forecasting', 'Forward-looking financial plans for confident decisions.' ),
	'business-consulting' => array( 'Business Consulting', 'Practical advice for entrepreneurs navigating growth and change.' ),
);
$service_live_content = is_readable( __DIR__ . '/data/service-content-live.json' ) ? ( json_decode( file_get_contents( __DIR__ . '/data/service-content-live.json' ), true ) ?: array() ) : array();
foreach ( $service_live_content as $service_slug => $service_entry ) {
	if ( isset( $services[ $service_slug ] ) && ! empty( $service_entry['title'] ) ) {
		$services[ $service_slug ][0] = $service_entry['title'];
	}
}
$card_images=array('corporate-tax-return'=>'service-corporate','business-tax-return'=>'service-corporate','bookkeeping'=>'service-books','financial-statements'=>'service-books','personal-tax-return'=>'service-personal','non-resident-tax-returns'=>'service-personal','trust-estate-tax-return'=>'service-personal','real-estate-tax-returns'=>'service-realestate','incorporation-business-registration'=>'page-about','tax-planning'=>'hero-planning','professional-corporations'=>'card-professional-corporation','hst-new-residential-rental-property-rebate'=>'card-hst-rebate','budgeting-forecasting'=>'card-forecasting','business-consulting'=>'card-consulting');
$base_path = rtrim( str_replace( '\\', '/', dirname( $_SERVER['SCRIPT_NAME'] ) ), '/' );
$request_path = trim( (string) parse_url( $_SERVER['REQUEST_URI'], PHP_URL_PATH ), '/' );
$base_trimmed = trim( $base_path, '/' );
if ( $base_trimmed && 0 === strpos( $request_path, $base_trimmed ) ) { $request_path = trim( substr( $request_path, strlen( $base_trimmed ) ), '/' ); }
$segments = $request_path ? explode( '/', $request_path ) : array();
$route_map = array( 'about' => 'about', 'services' => 'services', 'tax-checklists' => 'checklists', 'tax-resources' => 'resources', 'blog' => 'articles', 'tax-tips' => 'tips', 'tax-filing-deadlines' => 'deadlines', 'contact' => 'contact' );
$page = preg_replace( '/[^a-z0-9-]/', '', $_GET['page'] ?? ( $route_map[ $segments[0] ?? '' ] ?? 'home' ) );
$service = preg_replace( '/[^a-z0-9-]/', '', $_GET['service'] ?? ( ( $segments[0] ?? '' ) === 'services' ? ( $segments[1] ?? '' ) : '' ) );
$article = preg_replace( '/[^a-z0-9-]/', '', $_GET['article'] ?? ( ( $segments[0] ?? '' ) === 'blog' ? ( $segments[1] ?? '' ) : '' ) );
$contact_status = '';
if ( 'contact' === $page && 'POST' === ( $_SERVER['REQUEST_METHOD'] ?? 'GET' ) ) {
	$token = (string) ( $_POST['contact_token'] ?? '' );
	$name = trim( strip_tags( (string) ( $_POST['name'] ?? '' ) ) );
	$email = filter_var( (string) ( $_POST['email'] ?? '' ), FILTER_VALIDATE_EMAIL );
	$phone = trim( strip_tags( (string) ( $_POST['phone'] ?? '' ) ) );
	$service_interest = trim( strip_tags( (string) ( $_POST['service_interest'] ?? '' ) ) );
	$message = trim( strip_tags( (string) ( $_POST['message'] ?? '' ) ) );
	$valid_token = isset( $_SESSION['bajwa_contact_token'] ) && hash_equals( $_SESSION['bajwa_contact_token'], $token );
	if ( ! empty( $_POST['website'] ) ) { $contact_status = 'success'; }
	elseif ( ! $valid_token || ! $name || ! $email || ! $message ) { $contact_status = 'error'; }
	else {
		$body = "Name: $name\nEmail: $email\nPhone: $phone\nService: $service_interest\n\n$message";
		$headers = 'Reply-To: ' . $name . ' <' . $email . '>';
		$contact_status = @mail( 'info@bajwacpa.com', 'Website enquiry from ' . $name, $body, $headers ) ? 'success' : 'mail-error';
	}
}
if ( empty( $_SESSION['bajwa_contact_token'] ) ) { $_SESSION['bajwa_contact_token'] = bin2hex( random_bytes( 24 ) ); }
$blog_image = static function ( $slug ) {
	$rules = array( 'service-realestate' => array( 'real-estate', 'realestate', 'property', 'rental' ), 'service-books' => array( 'gst', 'hst', 'rates', 'bookkeep', 'financial-statement' ), 'service-personal' => array( 'personal', 'cerb', 'individual', 'income-tax' ), 'service-corporate' => array( 'corporate', 'business', 'company' ) );
	foreach ( $rules as $image => $terms ) { foreach ( $terms as $term ) { if ( false !== strpos( $slug, $term ) ) { return $image; } } }
	$images = array( 'service-corporate', 'service-personal', 'service-realestate', 'service-books', 'card-forecasting', 'card-consulting' );
	return $images[ abs( crc32( $slug ) ) % count( $images ) ];
};
$blog_posts = ( $article || in_array( $page, array( 'blog', 'articles' ), true ) )
	? ( json_decode( file_get_contents( __DIR__ . '/data/posts.json' ), true ) ?: array() )
	: array();
$base = $base_path . '/';
$pretty_routes = array( 'about' => 'about/', 'services' => 'services/', 'checklists' => 'tax-checklists/', 'resources' => 'tax-resources/', 'articles' => 'blog/', 'blog' => 'blog/', 'tips' => 'tax-tips/', 'deadlines' => 'tax-filing-deadlines/', 'contact' => 'contact/' );
$url = static function ( $target = 'home' ) use ( $base, $pretty_routes ) { return htmlspecialchars( $base . ( 'home' === $target ? '' : ( $pretty_routes[ $target ] ?? $target . '/' ) ), ENT_QUOTES, 'UTF-8' ); };
$service_url = static function ( $slug ) use ( $base ) { return htmlspecialchars( $base . 'services/' . $slug . '/', ENT_QUOTES, 'UTF-8' ); };
$article_url = static function ( $slug ) use ( $base ) { return htmlspecialchars( $base . 'blog/' . $slug . '/', ENT_QUOTES, 'UTF-8' ); };
$arrow = '<svg aria-hidden="true" viewBox="0 0 24 24"><path d="M5 12h14M13 6l6 6-6 6"/></svg>';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base href="<?php echo htmlspecialchars($base_path.'/'); ?>"><title>Bajwa CPA Professional Corporation</title><meta name="description" content="Professional tax, accounting and advisory services in Brampton and the Greater Toronto Area."><script>document.documentElement.classList.add('js')</script><?php if ( 'home' === $page && ! $article && ! $service ) : ?><link rel="preload" as="image" href="assets/images/hero-clarity.jpg" imagesrcset="assets/images/hero-clarity-960.jpg 960w, assets/images/hero-clarity-1280.jpg 1280w, assets/images/hero-clarity.jpg 1672w" imagesizes="100vw" fetchpriority="high"><?php endif; ?><link rel="stylesheet" href="assets/css/site.css"></head><body><div class="site-loader" data-site-loader aria-hidden="true"><div class="site-loader__mark"><span class="site-loader__logo"><img src="assets/images/bajwa-logo.png" width="250" height="68" alt=""></span><i aria-hidden="true"></i></div><div class="site-loader__accent" aria-hidden="true"><span></span><span></span><span></span></div><p>Loading your next page</p></div><div class="scroll-progress" aria-hidden="true"></div><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="utility"><div class="container utility__inner"><span>Trusted tax &amp; accounting advice across the GTA</span><div><a href="tel:4169070568">416-907-0568</a><span aria-hidden="true">•</span><a href="mailto:info@bajwacpa.com">info@bajwacpa.com</a></div></div></div><div class="container navbar"><a class="brand" href="<?php echo $url(); ?>" aria-label="Bajwa CPA home"><img src="assets/images/bajwa-logo.png" width="250" height="68" alt="Bajwa CPA Professional Corporation"></a><button class="menu-toggle" type="button" aria-controls="primary-menu" aria-expanded="false"><span></span><span></span><span></span><span class="screen-reader-text">Open menu</span></button><nav class="primary-nav" aria-label="Primary navigation"><ul id="primary-menu" class="menu"><li><a href="<?php echo $url(); ?>">Home</a></li><li><a href="<?php echo $url('about'); ?>">About Us</a></li><li class="menu-item-has-children"><a href="<?php echo $url('services'); ?>">Services</a><ul class="sub-menu"><?php foreach($services as $slug=>$item): ?><li><a href="<?php echo $service_url($slug); ?>"><?php echo htmlspecialchars($item[0]); ?></a></li><?php endforeach; ?></ul></li><li><a href="<?php echo $url('checklists'); ?>">Tax Checklists</a></li><li class="menu-item-has-children"><a href="<?php echo $url('resources'); ?>">Tax Resources</a><ul class="sub-menu"><li><a href="<?php echo $url('articles'); ?>">Articles</a></li><li><a href="<?php echo $url('tips'); ?>">Tax Tips</a></li><li><a href="<?php echo $url('deadlines'); ?>">Tax Filing Deadlines</a></li><li><a href="<?php echo $url('faq'); ?>">FAQ</a></li></ul></li><li><a href="<?php echo $url('contact'); ?>">Contact Us</a></li></ul></nav><a class="button button--navy navbar__cta" href="<?php echo $url('contact'); ?>">Let's talk</a></div></header>
<?php if ( $article ) : require __DIR__ . '/standalone-article.php'; ?>
<?php elseif ( $service && isset( $services[$service] ) ) : $item=$services[$service]; ?>
<?php $image_map=array('corporate-tax-return'=>'service-corporate','business-tax-return'=>'service-corporate','bookkeeping'=>'service-books','financial-statements'=>'service-books','personal-tax-return'=>'service-personal','non-resident-tax-returns'=>'service-personal','trust-estate-tax-return'=>'service-personal','real-estate-tax-returns'=>'service-realestate','incorporation-business-registration'=>'page-about','tax-planning'=>'hero-planning'); $header_image=$image_map[$service]??'service-corporate'; ?>
<main id="main"><header class="page-hero page-hero--image page-hero--service"><div class="page-hero__media"><img class="page-hero__image" src="assets/images/<?php echo $header_image; ?>.jpg" srcset="assets/images/<?php echo $header_image; ?>-960.jpg 960w, assets/images/<?php echo $header_image; ?>-1280.jpg 1280w, assets/images/<?php echo $header_image; ?>.jpg 1672w" sizes="100vw" width="1672" height="941" alt="" fetchpriority="high"><span class="page-hero__overlay"></span></div><div class="container page-hero__content"><p class="eyebrow">Professional services</p><h1><?php echo htmlspecialchars($item[0]); ?></h1><p class="page-hero__intro"><?php echo htmlspecialchars($item[1]); ?></p></div></header><article class="section"><div class="container content-with-aside"><div class="prose"><?php echo $service_live_content[$service]['content'] ?? '<p>Contact Bajwa CPA for professional guidance tailored to your situation.</p>'; ?><div class="inline-cta"><p class="eyebrow">A clear next step</p><h2>Get advice tailored to your situation.</h2><a class="button button--gold" href="<?php echo $url('contact'); ?>">Book a conversation <?php echo $arrow; ?></a></div></div><aside><span class="aside-kicker">CPA</span><p class="eyebrow">Need guidance?</p><h2>Talk with a CPA.</h2><p>Get clear advice based on your specific situation.</p><a class="button button--navy" href="<?php echo $url('contact'); ?>">Contact us</a><a class="aside-phone" href="tel:4169070568">416-907-0568</a></aside></div></article></main>
<?php elseif ( 'home' === $page ) : require __DIR__ . '/standalone-home.php'; ?>
<?php elseif ( false ) : ?>
<main id="main"><section class="hero" data-carousel aria-roledescription="carousel" aria-label="Featured services"><div class="hero__slides">
<?php $slides=array(array('hero-clarity','Chartered Professional Accountants','Clarity for every financial decision.','Tax, accounting and advisory support built around your goals—not a one-size-fits-all answer.','Book a consultation','contact'),array('hero-planning','Strategic Tax Planning','Plan today. Grow with confidence.','Year-round advice that helps business owners protect cash flow, reduce surprises and move forward.','Explore tax planning','services'),array('hero-advisory','Accounting & Advisory','Your business deserves a clear view.','Reliable books, meaningful financial reporting and practical advice from a team that understands your business.','View our services','services')); foreach($slides as $i=>$s): ?>
<article class="hero__slide<?php echo $i===0?' is-active':''; ?>" data-slide role="group" aria-roledescription="slide" aria-label="<?php echo ($i+1).' of 3'; ?>" aria-hidden="<?php echo $i===0?'false':'true'; ?>"><img class="hero__image" src="assets/images/<?php echo $s[0]; ?>.jpg" srcset="assets/images/<?php echo $s[0]; ?>-960.jpg 960w, assets/images/<?php echo $s[0]; ?>-1280.jpg 1280w, assets/images/<?php echo $s[0]; ?>.jpg 1672w" sizes="100vw" alt="" width="1672" height="941" <?php echo $i===0?'fetchpriority="high" loading="eager"':'loading="lazy" decoding="async"'; ?>><div class="hero__veil"></div><div class="container hero__inner"><div class="hero__content"><p class="hero__eyebrow"><?php echo $s[1]; ?></p><?php echo $i===0?'<h1':'<h2'; ?> class="hero__title"><?php echo $s[2]; ?><?php echo $i===0?'</h1>':'</h2>'; ?><p class="hero__copy"><?php echo $s[3]; ?></p><a class="button button--gold" href="<?php echo $url($s[5]); ?>"><?php echo $s[4].' '.$arrow; ?></a></div></div></article><?php endforeach; ?></div><div class="container hero__controls"><button class="hero__arrow" type="button" data-prev aria-label="Previous slide">←</button><div class="hero__dots" role="tablist" aria-label="Choose slide"><button role="tab" data-dot="0" aria-label="Show slide 1" aria-selected="true"></button><button role="tab" data-dot="1" aria-label="Show slide 2" aria-selected="false"></button><button role="tab" data-dot="2" aria-label="Show slide 3" aria-selected="false"></button></div><button class="hero__arrow" type="button" data-next aria-label="Next slide">→</button></div></section>
<section class="trust-strip"><div class="container trust-grid"><div><strong>500+</strong><span>Recurring clients</span></div><div><strong>1,000+</strong><span>Returns processed</span></div><div><strong>10+</strong><span>Years of experience</span></div><div><strong>Year-round</strong><span>Responsive support</span></div></div></section>
<section class="section intro"><div class="container split"><div><p class="eyebrow">Your finances, thoughtfully managed</p><h2>Professional guidance with a personal point of view.</h2></div><div><p class="lead">Bajwa CPA helps individuals, entrepreneurs and established companies navigate Canadian tax and accounting with clarity.</p><p>We combine detailed technical work with advice that is direct, practical and shaped around your goals.</p><a class="text-link" href="<?php echo $url('about'); ?>">Meet Bajwa CPA <?php echo $arrow; ?></a></div></div></section>
<section class="section section--mist"><div class="container"><div class="section-heading"><div><p class="eyebrow">How we can help</p><h2>Accounting built around real life and real business.</h2></div><a class="text-link" href="<?php echo $url('services'); ?>">View all services <?php echo $arrow; ?></a></div><div class="service-grid"><?php foreach(array_slice($services,0,6,true) as $slug=>$item): ?><a class="service-card" href="<?php echo $service_url($slug); ?>"><h3><?php echo htmlspecialchars($item[0]); ?></h3><p><?php echo htmlspecialchars($item[1]); ?></p><span class="service-card__arrow"><?php echo $arrow; ?></span></a><?php endforeach; ?></div></div></section>
<section class="section value"><div class="container split split--center"><div class="value__panel"><p class="eyebrow">Why clients choose us</p><h2>Calm expertise when the details matter.</h2><ul class="check-list"><li><span>✓</span><span><strong>Personal attention</strong>Advice shaped to your circumstances.</span></li><li><span>✓</span><span><strong>Current expertise</strong>Guidance grounded in Canadian rules.</span></li><li><span>✓</span><span><strong>Year-round access</strong>Support before important decisions.</span></li></ul></div><blockquote><p>“We earn trust by taking every client and every question seriously.”</p><cite>Vaishali Bajwa, CPA, CGA</cite></blockquote></div></section></main>
<?php elseif ( 'blog' === $page || 'articles' === $page ) : require __DIR__ . '/standalone-blog.php'; ?>
<?php elseif ( in_array($page,array('tips','deadlines'),true) ) : require __DIR__ . '/standalone-resource.php'; ?>
<?php elseif ( 'contact' === $page ) : require __DIR__ . '/standalone-contact.php'; ?>
<?php elseif ( 'about' === $page ) : require __DIR__ . '/standalone-about.php'; ?>
<?php elseif ( 'checklists' === $page ) : require __DIR__ . '/standalone-checklists.php'; ?>
<?php else: $titles=array('about'=>'About Us','services'=>'Our Services','checklists'=>'Tax Checklists','resources'=>'Tax Resources','blog'=>'Blog Posts','articles'=>'Blog Posts','contact'=>'Contact Us'); $title=$titles[$page]??'Bajwa CPA'; ?>
<?php $page_image=$page==='contact'?'page-contact':($page==='about'?'page-about':($page==='services'?'service-corporate':'service-books')); ?>
<main id="main"><header class="page-hero page-hero--image"><div class="page-hero__media"><img class="page-hero__image" src="assets/images/<?php echo $page_image; ?>.jpg" srcset="assets/images/<?php echo $page_image; ?>-960.jpg 960w, assets/images/<?php echo $page_image; ?>-1280.jpg 1280w, assets/images/<?php echo $page_image; ?>.jpg 1672w" sizes="100vw" width="1672" height="941" alt="" fetchpriority="high"><span class="page-hero__overlay"></span></div><div class="container page-hero__content"><p class="eyebrow">Bajwa CPA Professional Corporation</p><h1><?php echo htmlspecialchars($title); ?></h1><p class="page-hero__intro">Clear, practical advice for the financial decisions that matter.</p></div></header><section class="section"><div class="container <?php echo $page==='services'?'service-grid service-grid--editorial':'prose'; ?>">
<?php if($page==='services'): $card_i=0; foreach($services as $slug=>$item): $card_i++; ?><a class="service-card <?php echo $card_i===1?'service-card--feature':''; ?>" href="<?php echo $service_url($slug); ?>"><span class="service-card__number"><?php echo str_pad($card_i,2,'0',STR_PAD_LEFT); ?></span><h2><?php echo htmlspecialchars($item[0]); ?></h2><p><?php echo htmlspecialchars($item[1]); ?></p><span class="service-card__arrow"><?php echo $arrow; ?></span></a><?php endforeach; elseif($page==='contact'): ?><div class="contact-card"><h2>Start a conversation</h2><p class="lead">Call or email our team to arrange a consultation.</p><strong>Phone</strong><a href="tel:4169070568">416-907-0568</a><strong>Email</strong><a href="mailto:info@bajwacpa.com">info@bajwacpa.com</a><strong>Office</strong><span>2 County Court Blvd, Suite 400<br>Brampton, Ontario L6W 3W8</span></div><?php elseif($page==='about'): ?><p class="lead">Bajwa CPA is a Chartered Professional Accounting firm serving businesses, families and individuals across the Greater Toronto Area.</p><h2>Professional advice, personal attention</h2><p>We provide high-quality, timely tax, accounting and advisory services. Our approach is practical, personal and built around long-term client relationships.</p><h2>Led by Vaishali Bajwa, CPA, CGA</h2><p>Our team combines current knowledge of Canadian tax rules with a clear, approachable style.</p><?php elseif($page==='checklists'): ?><p class="lead">Prepare for your appointment with the records commonly needed for accurate tax filing.</p><h2>Personal tax checklist</h2><ul><li>Income slips and RRSP receipts</li><li>Medical, childcare, tuition and donation receipts</li><li>Rental, investment and self-employment records</li><li>Prior-year Notice of Assessment</li></ul><h2>Business checklist</h2><ul><li>Bank and credit-card statements</li><li>Sales invoices and expense receipts</li><li>Payroll and GST/HST records</li><li>Prior-year financial statements</li></ul><?php elseif($page==='faq'): ?><details><summary>When should I contact a CPA?</summary><p>Before a major financial decision, business change or tax deadline.</p></details><details><summary>Do you work with individuals and companies?</summary><p>Yes. We serve individuals, corporations, investors and self-employed professionals.</p></details><details><summary>Can you help throughout the year?</summary><p>Yes. Our support extends well beyond tax season.</p></details><?php else: ?><p class="lead">Straightforward Canadian tax and accounting information to help you stay informed and prepared.</p><h2>Practical guidance from professionals</h2><p>Tax rules and deadlines can change. Contact our team for current information and advice tailored to your situation.</p><?php endif; ?></div></section></main><?php endif; ?>
<section class="closing-cta"><div class="container closing-cta__inner"><div><p class="eyebrow">Start with a conversation</p><h2>Bring clarity to your next financial decision.</h2></div><a class="button button--gold" href="<?php echo $url('contact'); ?>">Book a consultation <?php echo $arrow; ?></a></div></section><footer class="site-footer"><div class="container footer-grid"><div><img class="footer-logo" src="assets/images/bajwa-logo.png" width="250" height="68" alt="Bajwa CPA"><p>Professional tax, accounting and advisory services across the Greater Toronto Area.</p></div><div><h2>Contact</h2><address>2 County Court Blvd, Suite 400<br>Brampton, Ontario L6W 3W8</address><p><a href="tel:4169070568">416-907-0568</a><br><a href="mailto:info@bajwacpa.com">info@bajwacpa.com</a></p></div><div><h2>Explore</h2><ul><li><a href="<?php echo $url('about'); ?>">About Us</a></li><li><a href="<?php echo $url('services'); ?>">Services</a></li><li><a href="<?php echo $url('checklists'); ?>">Tax Checklists</a></li><li><a href="<?php echo $url('contact'); ?>">Contact</a></li></ul></div><div><h2>Office hours</h2><p>Monday–Friday<br>9:00 AM–5:00 PM</p></div></div><div class="container footer-bottom"><span>© <?php echo date('Y'); ?> Bajwa CPA Professional Corporation.</span><span>Chartered Professional Accountants</span></div></footer><script src="assets/js/site.js" defer></script></body></html>
