<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/** One-time migration of client-owned copy from the previous Bajwa CPA website. */
function bajwa_import_legacy_site_content() {
	if ( get_option( 'bajwa_legacy_content_version' ) >= 3 ) { return; }
	$about = get_page_by_path( 'about-us', OBJECT, 'page' );
	if ( $about ) {
		wp_update_post( array( 'ID' => $about->ID, 'post_content' => '<p class="lead">We want individuals, corporations, entrepreneurs and everyone in between across the GTA to feel that their tax and accounting professionals value their time, money and desire to live financially secure.</p><h2>The team at Bajwa CPA</h2><p>We provide personalized solutions for a wide range of accounting needs. Our reputation and long-standing client relationships have been built through hard work, integrity and professional talent.</p><p>As members of the Chartered Professional Accountants association, we stay current with changing laws and professional standards. Our pricing is fixed, our support is available year-round and we take every client deadline seriously.</p><h2>Why clients choose Bajwa CPA</h2><p>Our clients trust us with their livelihoods and financial well-being, and we take that responsibility seriously. We keep learning, sharpen our skills and offer a broad range of services so clients can receive coordinated advice from one professional team.</p><h2>We take our role seriously</h2><p>Chartered accountants and tax professionals play an important role in the community. We want every client who walks through our doors to feel that we care about their success and want what is best for them.</p>' ) );
		update_post_meta( $about->ID, '_bajwa_content_source', 'https://bajwacpa.com/about/' );
	}
	$service_content = array(
		'corporate-tax-return' => '<p>We provide corporate tax preparation and advice for companies across many sectors. By staying current with Canadian tax law, we help corporate clients file accurately, meet deadlines and make informed decisions.</p><h2>Corporate tax services</h2><ul><li>T2 corporate tax return preparation and filing</li><li>Tax schedules, instalments and year-end adjusting entries</li><li>T4 employment and T5 dividend slips</li><li>GST/HST returns and payroll remittances</li><li>Compilation financial statements</li><li>Monthly, quarterly or annual bookkeeping and general ledgers</li><li>Corporate tax planning and tax-minimization strategies</li></ul><h2>Personalized for your business</h2><p>We take time to understand each client’s business and provide professional services in a clear, timely and reliable way.</p>',
		'business-tax-return' => '<p>We assist sole proprietors, partnerships and unincorporated businesses with professional bookkeeping, accounting, GST/HST and income-tax filing services. We can also guide business registration and incorporation.</p><h2>Business tax services</h2><ul><li>Statement of Business or Professional Activities (T2125)</li><li>GST/HST return preparation and filing</li><li>Payroll services for employees</li><li>Bookkeeping, general ledgers and financial statements</li><li>Year-round business tax planning</li></ul><h2>Tailored to your small business</h2><p>Every business is different. We learn how yours operates and explain the work in a practical, easy-to-understand way.</p>',
		'bookkeeping' => '<p>Accurate, current books are critical for measuring growth, planning development and filing reliable year-end returns. We serve corporations, sole proprietors and unincorporated businesses with personalized one-to-one support.</p><h2>Accounting and bookkeeping support</h2><ul><li>Monthly, quarterly and annual bookkeeping</li><li>General ledgers and financial statement preparation</li><li>Accounting-system setup for new businesses</li><li>Compilation financial statements</li><li>Payroll processing</li><li>Accounts payable and receivable</li><li>Bank and credit-card reconciliations</li><li>Monthly financial reports</li></ul><p>Our QuickBooks ProAdvisor-certified team helps keep records timely and accurate so owners can understand their financial position and manage the business successfully.</p>',
		'personal-tax-return' => '<p>We provide high-quality personal income tax return preparation (T1 General) for a wide range of circumstances. Canadian tax rules change frequently, and professional preparation helps keep filings accurate and on time.</p><p>We assist clients with employment, interest, rental, employment-insurance and self-employment income, while identifying applicable deductions and credits.</p>',
		'non-resident-tax-returns' => '<p>Canadian non-residents can face specialized filing, withholding and reporting requirements. We assist property owners and other non-residents with the documentation and returns required for Canadian-source income.</p><h2>Non-resident support</h2><ul><li>NR4 information and withholding reporting</li><li>NR6 applications</li><li>Section 216 rental-income returns</li><li>T2062 clearance-certificate support for property dispositions</li><li>Rental income and expense reporting</li></ul>',
		'real-estate-tax-returns' => '<p>Real estate ownership and transactions can create rental-income reporting, capital-gain, principal-residence and GST/HST considerations. We help property owners, investors and real estate professionals organize their records and report transactions correctly.</p><h2>Real estate tax support</h2><ul><li>Rental income and expense reporting</li><li>Property purchase and disposition documentation</li><li>Capital-gain and principal-residence reporting</li><li>Non-resident rental and disposition filings</li><li>GST/HST rental-property rebate guidance</li></ul>',
		'trust-estate-tax-return' => '<p>Trust and estate administration brings important tax filings and deadlines. We assist trustees, executors and legal representatives with organized, sensitive support.</p><h2>Trust and estate services</h2><ul><li>T3 trust income tax and information returns</li><li>Final personal tax returns</li><li>Estate income and beneficiary reporting</li><li>Clearance-certificate support</li><li>Guidance on records and filing deadlines</li></ul>',
		'incorporation-business-registration' => '<p>Choosing the right structure affects tax, compliance and administration. We help entrepreneurs register or incorporate their businesses and understand the responsibilities that follow.</p><h2>Business setup support</h2><ul><li>Business-name registration</li><li>Federal or provincial incorporation support</li><li>CRA business-number and program accounts</li><li>GST/HST and payroll registration</li><li>Professional corporation setup</li><li>Initial accounting and bookkeeping guidance</li></ul>',
		'financial-statements' => '<p>Reliable financial statements make it easier for owners, lenders and other users to understand what the numbers mean. They are an important tool for financing, compliance and sound business decisions.</p><h2>Compilation financial statements</h2><p>We compile financial information provided by management into professional financial statements and proposed year-end adjusting entries. These statements may support lending, a business purchase or sale, and other external requirements.</p>',
		'tax-planning' => '<p>Tax planning is most valuable before a filing deadline or major transaction. We help individuals and businesses review their structure, timing and available options so decisions are made with a clearer understanding of the tax consequences.</p><h2>Forward-looking advice</h2><ul><li>Owner-manager compensation planning</li><li>Corporate and personal instalment planning</li><li>Business structure and incorporation considerations</li><li>Investment and real estate transaction planning</li><li>Year-end tax-minimization strategies</li></ul>',
		'budgeting-forecasting' => '<p>A budget is an annual financial plan that identifies desired results, while a forecast projects expected results during the year. Used together, they help business owners compare plans with performance and respond earlier.</p><h2>Planning support</h2><ul><li>Annual operating budgets</li><li>Cash-flow projections</li><li>Scenario and sensitivity analysis</li><li>Performance monitoring</li><li>Financing and growth projections</li></ul>',
		'business-consulting' => '<p>Whether a business is established or just starting, owners make important decisions every day. Our advisory and business-consulting services help companies evaluate opportunities, improve performance and work toward financial success.</p><h2>Advice for every stage</h2><ul><li>Startup and structure decisions</li><li>Financial performance review</li><li>Cash-flow and profitability analysis</li><li>Growth planning</li><li>Practical owner-manager guidance</li></ul>',
	);
	$live_content = array();
	$live_content_file = BAJWA_PREMIUM_DIR . 'data/service-content-live.json';
	if ( is_readable( $live_content_file ) ) {
		$live_content = json_decode( file_get_contents( $live_content_file ), true ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		foreach ( (array) $live_content as $slug => $entry ) { if ( ! empty( $entry['content'] ) ) { $service_content[ $slug ] = $entry['content']; } }
	}
	foreach ( $service_content as $slug => $content ) {
		$post = get_page_by_path( $slug, OBJECT, 'service' );
		if ( ! $post ) { continue; }
		$update = array( 'ID' => $post->ID, 'post_content' => $content, 'post_excerpt' => '' );
		if ( ! empty( $live_content[ $slug ]['title'] ) ) { $update['post_title'] = $live_content[ $slug ]['title']; }
		wp_update_post( $update );
		$source_url = isset( $live_content[ $slug ]['source_url'] ) ? $live_content[ $slug ]['source_url'] : 'https://bajwacpa.com/service/' . $slug . '/';
		update_post_meta( $post->ID, '_bajwa_content_source', $source_url );
	}
	update_option( 'bajwa_legacy_content_version', 3 );
}
add_action( 'admin_init', 'bajwa_import_legacy_site_content' );
